# -*- coding: UTF-8 -*-
"""
@Author: ryannnwang
@CreateDate: 2023-07-05
@File: instruction_config
@Project: Yale summer Project
"""
INSTRUCTION_VERIFY = """
You are given a question-answer (QA) pair. Your task is to verify the accuracy and correctness of the answer. \
If the answer is not accurate or correct, re-generate a more accurate and correct answer based on the given question. \
If the answer is already accurate and correct, return a more formal answer. Both you should make the output answer \
better suit training a Large Language Model. Please make sure you read and understand these instructions carefully. \
Keep this document open while reviewing, and refer to it as needed.\n
The following is format of the input and output, the output must follow the specified format:\n
**Input:**\n
Question: <insert question here>\n
Answer: <insert answer here>\n
**Output:**\n
If the given answer is not accurate or correct:\n
```
<a new answer generated by ChatGPT>
```
If the given answer is already accurate and correct:\n
```
<A newly generated answer by ChatGPT that is more formal and easier to understand>
``` 
Criteria:
1. The input question should remain unchanged. \n
2. Please note that the new answer generated by ChatGPT should be as relevant and precise as possible, \
while also being accurate and correct.\n
3. The new answer generated by ChatGPT should be grammatically correct and fluent.\n
4. Do not make the input answer same as the output answer.\n
5. Do not output the Question again, you only need to output the new answer text generated by ChatGPT.\n
6. Optimize the answer to better suit training a Large Language Model.\n

### Example1:\n
**Input:**\n
Question: I'm interested in learning more about biomedical research. Can you tell me about any recent breakthroughs in the field?\n
Answer: Yes, there have been many recent breakthroughs in computer research. Here are a few examples:
1. GPT-3: In 2020, OpenAI released GPT-3, a language model with 175 billion parameters that can generate \
human-like text, answer questions, and perform tasks like translation and summarization.\n
2. AlphaFold: In 2020, DeepMind's AlphaFold was able to predict the 3D structure of proteins with remarkable \
accuracy, which could revolutionize drug discovery and other fields.\n
3. Quantum Computing: In 2021, Google announced that its Sycamore quantum processor had achieved "quantum supremacy," \
performing a calculation that would take the world's fastest supercomputer thousands of years to complete.\n
**Output:**\n
1. CRISPR gene editing: In 2020, scientists used CRISPR gene editing to cure sickle cell disease in mice. This breakthrough \
could pave the way for a cure for the disease in humans.
2. mRNA vaccines: The COVID-19 pandemic has brought mRNA vaccines into the spotlight. These vaccines use a small piece of \
genetic material to teach the body to recognize and fight the virus. They have been shown to be highly effective and could \
be used to develop vaccines for other diseases in the future.
3. Artificial organs: Researchers are making progress in developing artificial organs that can be used to replace damaged or \
diseased organs. In 2020, scientists created a functioning mini-liver using human cells and a 3D printer.
4. Cancer immunotherapy: Immunotherapy is a type of cancer treatment that uses the body's own immune system to fight cancer. \
In 2020, researchers discovered a new type of immune cell that could be used to improve the effectiveness of immunotherapy.
5. Brain-computer interfaces: Brain-computer interfaces (BCIs) allow people to control computers or other devices using their \
thoughts. In 2020, researchers developed a BCI that allowed a person with paralysis to type using their thoughts.
These are just a few examples of recent breakthroughs in biomedical research. The field is constantly evolving, and there are \
always new discoveries being made.

### Example2:
**Input:**
Question: That's really fascinating! Can you tell me more about how CRISPR gene editing works?
Answer: Sure! CRISPR (Clustered Regularly Interspaced Short Palindromic Repeats) is a gene editing technique that \
allows scientists to make precise changes to DNA sequences. It works by using a protein called Cas9, which acts like \
a pair of molecular scissors, to cut the DNA at a specific location. Once the DNA is cut, the cell's natural repair \
mechanisms can be used to either delete or replace the DNA sequence.
To use CRISPR, scientists first design a small piece of RNA that matches the DNA sequence they want to target. This \
RNA molecule is then combined with the Cas9 protein and introduced into the cells that they want to edit. The RNA \
molecule guides the Cas9 protein to the specific location in the DNA where it should make the cut.
Once the DNA is cut, the cell's natural repair mechanisms can be used to either delete or replace the DNA sequence. \
This allows scientists to make precise changes to the DNA, such as correcting genetic mutations that cause diseases.
CRISPR has revolutionized the field of genetic engineering because it is faster, cheaper, and more precise than \
previous gene editing techniques. It has the potential to be used to treat a wide range of genetic diseases, \
including sickle cell disease, cystic fibrosis, and Huntington's disease. However, there are also ethical concerns \
about the use of CRISPR, particularly when it comes to editing the DNA of human embryos.
**Output:**
Sure! CRISPR (Clustered Regularly Interspaced Short Palindromic Repeats) is a gene editing technique that \
allows scientists to make precise changes to DNA sequences. It works by using a protein called Cas9, which acts like \
a pair of molecular scissors, to cut the DNA at a specific location. Once the DNA is cut, the cell's natural repair \
mechanisms can be used to either delete or replace the DNA sequence.
To use CRISPR, scientists first design a small piece of RNA that matches the DNA sequence they want to target. This \
RNA molecule is then combined with the Cas9 protein and introduced into the cells that they want to edit. The RNA \
molecule guides the Cas9 protein to the specific location in the DNA where it should make the cut.
Once the DNA is cut, the cell's natural repair mechanisms can be used to either delete or replace the DNA sequence. \
This allows scientists to make precise changes to the DNA, such as correcting genetic mutations that cause diseases.
CRISPR has revolutionized the field of genetic engineering because it is faster, cheaper, and more precise than \
previous gene editing techniques. It has the potential to be used to treat a wide range of genetic diseases, \
including sickle cell disease, cystic fibrosis, and Huntington's disease. However, there are also ethical concerns \
about the use of CRISPR, particularly when it comes to editing the DNA of human embryos.
"""
